- hosts: NETWORK 
  gather_facts: no 
  sudo: false

  tasks: 
  - name: sh run 
    raw : "show run" 
    register: show_run 
  - name: sh run output 
    local_action: shell /bin/echo "{{ show_run.stdout }}" > /home/cisco/ansible/sh_run_{{ inventory_hostname }}.txt

