# Main tasks to configure panos devices

- name: Add some security rules to the firewall
  hosts: paloalto
  connection: local
  gather_facts: False

  tasks:
    - name: check if PAN-OS device is ready for being configured
      panos_check:
        ip_address: '{{ inventory_hostname }}'
        username: '{{ ansible_ssh_user }}'
        password: '{{ ansible_ssh_pass }}'

    - name: Add test rule 1 to the firewall
      panos_security_rule:
        ip_address: '{{ inventory_hostname }}'
        username: '{{ ansible_ssh_user }}'
        password: '{{ ansible_ssh_pass }}'
        operation: 'add'
        rule_name: 'Ansible test 1'
        description: 'An Ansible test rule'
        source_zone: ['internal']
        destination_zone: ['external']
        source_ip: ['host-1.2.3.4']
        source_user: ['any']
        destination_ip: ['any']
        category: ['any']
        application: ['any']
        service: ['service-xyz']
        hip_profiles: ['any']
        action: 'allow'

    - name: Add test rule 2 to the firewall
      panos_security_rule:
        ip_address: '{{ inventory_hostname }}'
        username: '{{ ansible_ssh_user }}'
        password: '{{ ansible_ssh_pass }}'
        operation: 'add'
        rule_name: 'Ansible test 2'
        description: 'Another Ansible test rule'
        source_zone: ['internal']
        source_ip: ['range-192.168.100.100-200']
        source_user: ['any']
        hip_profiles: ['any']
        destination_zone: ['external']
        destination_ip: ['any']
        category: ['any']
        application: ['any']
        service: ['service-abc']
        action: 'allow'
        group_profile: 'default'

    - name: Add test rule 3 to the firewall
      panos_security_rule:
        ip_address: '{{ inventory_hostname }}'
        username: '{{ ansible_ssh_user }}'
        password: '{{ ansible_ssh_pass }}'
        operation: 'add'
        rule_name: 'Ansible test 3'
        description: 'Yet another Ansible test rule'
        source_zone: ['internal']
        source_ip: ['net-10.0.0.0-8']
        source_user: ['any']
        hip_profiles: ['any']
        destination_zone: ['external']
        destination_ip: ['any']
        category: ['any']
        application: ['any']
        service: ['test-service-group']
        action: 'allow'
